// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Chirp struct {
	ID        string
	UserID    string
	Body      string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID             string
	Email          string
	CreatedAt      time.Time
	UpdatedAt      time.Time
	HashedPassword string
}
