// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"
)

type Querier interface {
	ChangeEmailPassword(ctx context.Context, arg ChangeEmailPasswordParams) error
	CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteChirp(ctx context.Context, arg DeleteChirpParams) error
	GetAllChirps(ctx context.Context) ([]Chirp, error)
	GetChirp(ctx context.Context, id string) (Chirp, error)
	GetPassword(ctx context.Context, email string) (string, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	ResetUsersTable(ctx context.Context) error
	UpgradeUserToChirpy(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
