// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package database

import (
	"context"
)

const changeEmailPassword = `-- name: ChangeEmailPassword :exec
update users
set email = $1,
hashed_password = $2,
updated_at = now()
where id = $3
`

type ChangeEmailPasswordParams struct {
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
	ID             string `json:"id"`
}

func (q *Queries) ChangeEmailPassword(ctx context.Context, arg ChangeEmailPasswordParams) error {
	_, err := q.exec(ctx, q.changeEmailPasswordStmt, changeEmailPassword, arg.Email, arg.HashedPassword, arg.ID)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, hashed_password, updated_at, created_at)
VALUES (gen_random_uuid(), $1, $2, NOW(), NOW())
RETURNING id, email, created_at, updated_at, hashed_password, is_chirpy_red
`

type CreateUserParams struct {
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser, arg.Email, arg.HashedPassword)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const getPassword = `-- name: GetPassword :one
select hashed_password from users where email = $1
`

func (q *Queries) GetPassword(ctx context.Context, email string) (string, error) {
	row := q.queryRow(ctx, q.getPasswordStmt, getPassword, email)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, created_at, updated_at, hashed_password, is_chirpy_red FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedPassword,
		&i.IsChirpyRed,
	)
	return i, err
}

const resetUsersTable = `-- name: ResetUsersTable :exec
DELETE FROM users
`

func (q *Queries) ResetUsersTable(ctx context.Context) error {
	_, err := q.exec(ctx, q.resetUsersTableStmt, resetUsersTable)
	return err
}

const upgradeUserToChirpy = `-- name: UpgradeUserToChirpy :exec
update users
set is_chirpy_red = true,
updated_at = now()
where id = $1
`

func (q *Queries) UpgradeUserToChirpy(ctx context.Context, id string) error {
	_, err := q.exec(ctx, q.upgradeUserToChirpyStmt, upgradeUserToChirpy, id)
	return err
}
